### PR TITLE
Added the option to select the focal length type

### PR DESCRIPTION
**Pull request by YoshikiOhtani**
This pull request implements the option "focal_length_choice" to select the "nominal" or "effective" focal length when constructing the SubarrayDescription. Since ctapipe v0.12 which is used in the current version of magic-cta-pipe gives the "nominal" focal length by default for simulation data, here the default value is also set to the "nominal". This pull request is related to the one #cta-observatory/magic-cta-pipe#72.

### CODE REVIEW

**Comment by aleberti** [comment]
Thanks for the change. I have some comments:
- please add some tests for this new piece of code. I can make a quick commit tomorrow to fix the automatic tests, so that you can merge it from master and check that they run fine
- why the default value should be nominal? To me it makes sense that effective should be used. If you choose nominal at DL0 to DL1 level, then you will keep it for all the chain, so stereo parameters will be calculated using that focal length, not the effective one (unless you change it, but manually). This comment applies also to the other PR open in MCP
- you may check the current open PR in ctapipe-io-lst to have a similar implementation: https://github.com/cta-observatory/ctapipe_io_lst/pull/149 . Also there, the effective focal length is chosen as default

**Review by jsitarek — COMMENTED** [review]
I'm also for keeping "effective" as default, no other comments from me.

**Comment by aleberti** [comment]
@YoshikiOhtani I updated the master so that automatic tests work again. Please merge it in your branch so that we can check that tests pass here as well.

**Comment by YoshikiOhtani** [comment]
Thanks for your review, and I changed the default to "effective". The reason why I chose "nominal" as default is that it would be safe to follow the default of SimTelEventSource and LSTEventSource. But as Alessio mentioned now LST is going to use the effective one for the default, I'm fine with this change. 

@aleberti, I implemented a test function and it passed successfully, but there is something "Codacy Static Code Analysis — This pull request quality could be better." which I'm not sure what happens. Could you please have a look?

**Comment by aleberti** [comment]
Thanks! About the "failing" check, do not worry, they are just warnings about the use of assert, no actual error. Fine for me to merge it.

**Pull request merged**
