### PR TITLE
Adapt mono real data

### PR DESCRIPTION
**Pull request by aleberti**
This PR is needed if one wants to read MAGIC data taken in mono mode (either M1 only or M2 only). This allows for example to analyze M1+LST1 or M2+LST1 data with `magic-cta-pipe`.

### CODE REVIEW

**Comment by aleberti** [comment]
@jsitarek about MC data, how should this be handled? Stereo MC files as far as I remember contain both mono and stereo events (trigger pattern 0 and 1 respectively). So if we want to make mono analysis using stereo MC files we should take them both right? I checked also some M2 mono MC files produced for 2014, and I see that the trigger pattern is always 1 (except for the first event; this is the same as in stereo MC files), but the difference is in the stereo trigger id which is always 0 for mono MC files. Of course this applies only if one uses MAGIC MC data, with simtel MC this should be straightforward

**Comment by YoshikiOhtani** [comment]
Hi @aleberti, I also faced the issue that `is_stereo` is flagged as `True` even if the input data is mono trigger, due to the difference of the prescaler types. It would be great for me to fix this issue as soon as possible, because I would like to avoid the joint observation data taken with MAGIC mono trigger setting for my study (which sometimes happened in the past actually). Do you think it is OK to merge this branch now, and open another pull request to adapt MAGIC MCs?

**Comment by YoshikiOhtani** [comment]
By the way I checked one mono observation data file and found that `MRawEvtHeader.fStereoEvtNumber` is always set to 0, so it would be needed to use `MRawEvtHeader.fDAQEvtNumber` for the event IDs of mono events.

**Comment by aleberti** [comment]
Hi Yoshiki, about the merging, I guess it can be done, I will do it tomorrow since today I am busy in a business trip. About the event ID, yes, I also noticed the same for fStereoEvtNumber. However, fDAQEvtNumber is not good. The problem is that while the former is unique within a run, the latter is not. You can check it easily by taking the DAQ event number of events belonging to two different subruns of the same run. I guess in MARS it is not a problem because there is no coincidence to make. But for your coincidence script it is because it is expected that each event has different IDs (within the same run). So another solution should be implemented. The easiest would be to have just an incremental ID for each event, done at the ctapipe_io_magic level.

**Comment by YoshikiOhtani** [comment]
Hi Alessio, thanks for your explanation, indeed I checked that the DAQ ID is reset in every subrun data, which is not good for the event coincidence. If we process all the subrun files of the same run ID at once (with `--process-run` option), I think the easiest solution is to assign the IDs produced by, for example, `enumerate` function. However, when we process the data subrun-wise (without `--process-run` option), this cannot be used. It may be good to use the run and subrun IDs, for example, `event ID = int(str(run_id) + str(subrun_id) + str(daq_id)) `, but it makes the digits of the event ID larger...

**Comment by aleberti** [comment]
I was looking into this issue just now. So, we can go along your final suggestion, with some modification. In mono mode, run numbers are of the type 0TDDDDDD, where T is the telescope number (1 or 2), and D is an integer (0 to 9). Subrun numbers are usually 0DD. Since subruns have a maximum number of events (I just checked and this maximum number of events per subrun is ~17000), depending on the rate, a given run will have more or less subruns (more if taken with SumT). So, given this information, we could get the event id as:

```
event_id = int(f"{run_id-tel_id*1000000}{subrun_id:03}{daq_id:05}")
```

In this way, if we have e.g. run_id=2005492, subrunid=013 and daq_id=185, we would have `event_id=549201300185`. Or, we may forget about the run_id, and just do:

```
event_id = int(f"{subrun_id}{daq_id:05}")
```

which for the example above would mean `event_id=1300185`, and it would be different depending on the subrun_id for events with the same daq_id. This way the number is not too big. Moreover, this event_id is always the same if data are reprocessed.

What do you think?

**Comment by aleberti** [comment]
Find an implementation in 77d6a6e8bb45b8a9e174317fdecb3968f083290c. It seems it works well for real data. Please try and let me know.

**Comment by YoshikiOhtani** [comment]
Hi Alessio, thank you for looking into this, and as you already implemented, I also go for the second solution, since it already separates of the events with the same DAQ ID but different subrun IDs. I will try it now and let you know.

**Comment by YoshikiOhtani** [comment]
I checked with a few mono data files and confirmed it worked fine. Here are just some minor comments:

- I would rename the key "stereo_event_number" to "event_number", since in case of mono data it is not stereo event number anymore.
- I would just add a small comment in the code why we use such a definition for mono event IDs to avoid a future confusion.

If it is OK for you, could you please merge to the master, and create a new tag to the master, so that we can use the bug fix version in magic-cta-pipe? Thank you very much!

**Comment by aleberti** [comment]
Hi Yoshiki, I implemented your suggestions. In the meanwhile I was also looking into how to discriminate between mono/stereo and std trigger/SumT MC data. So I added code to do that as well. I tried on some mono and SumT calibrated MC data and it works fine. I will merge this now to master and open another PR to complete the (MAGIC) MC handling in the case of mono.

**Comment by aleberti** [comment]
v0.4.6 created and uploaded to PyPI.

**Comment by YoshikiOhtani** [comment]
Thanks Alessio, then I will change the required version of ctapipe_io_magic in the magic-cta-pipe environment now.

**Pull request merged**
