### PR TITLE
Add a function to get the bad RMS pixels mask 

### PR DESCRIPTION
**Pull request by YoshikiOhtani**
The bad pixels are currently searched by the bad pixels calculator implemented in magic-cta-pipe, but this can be done in the `MAGICEventSource` and would be better to do so and store the pixel masking information in the `ArrayEventContainer` (`container.event.mon[tel_id].pixel_status.pedestal_failing_pixels`), so I implemented the function.

### CODE REVIEW

**Comment by YoshikiOhtani** [comment]
OK so let me describe more detail about this pull request. First of all, this branch is created from the read-multiple-files branch and so all the commits by Alessio are coming from that, not related to this pull request. Then, as I mentioned in the issue of magic-cta-pipe (https://github.com/cta-observatory/magic-cta-pipe/issues/11), I looked into the source codes of the MAGIC_Badpixels.py and found that everything can be done inside the MAGICEventSource. This is because:
- the `get_deadpixel_mask` function only reads `event.mon.tel[tel_id].pixel_status.hardware_failing_pixels` and nothing is done. 
- the `get_badrmspixel_mask` function seems to calculate the charge std outlier but all the necessary information are stored in `ArrayEventContainer`, which is created by the `MAGICEventSource`.
- The ArrayEventContainer has a space to store the mask of the badrmspixels, which is `event.mon.tel[tel_id].pixel_status.pedestal_failing_pixels`, and so it would be good to get the mask inside the `MAGICEventSource` and store it in that space. 

So with this pull request, `event.mon.tel[tel_id].pixel_status.pedestal_failing_pixels` contains the arrays with the shape of (3, 1089). The first axis means the pedestal type, i.e., 0, 1, 2 are "PedestalFundamental", "PedestalFromExtractor" and "PedestalFromExtractorRndm", respectively, which will be selected by analyzers (default setting was "PedestalFromExtractorRndm"). Since the mask will be used for the MAGICCleaning, we can add a config about the pedestal type. For getting the bad RMS pixels, we need `pedestal_level` and `pedestal_level_variance` settings, and now I just put the default values(400 and 4.5) inside the function. I'm not sure if we need to change the values by ourself. 

Finally the bad pixels mask can be obtained as follows (in case of using "PedestalFromExtractorRndm"):
```
unsuitable_mask = np.logical_or(
    event.mon.tel[tel_id].pixel_status.hardware_failing_pixels,
    event.mon.tel[tel_id].pixel_status.pedestal_failing_pixels[2]
)
```
Any comments are welcome. I confirmed the new function reproduces the results of MAGIC_Badpixels.py, but cross-checks are also welcome. If this is approved, we can simply remove the MAGIC_Badpixels.py from magic-cta-pipe repository.

**Comment by aleberti** [comment]
Hi, I think that you should rebase your branch now that #31 was merged into master (note that I also added a commit yesterday to fix some MC stuff). In that way I should be able to see the correct diff (now I see both my changes and yours).

**Comment by YoshikiOhtani** [comment]
Hi Alessio, sure, will do it soon.

**Comment by YoshikiOhtani** [comment]
I just merged the master branch to this one.

**Comment by aleberti** [comment]
Please run the tests locally on your machine (manually download the test data from PIC for the moment, if you do not have it already), there is one test failing which requires a fix.

**Comment by YoshikiOhtani** [comment]
Hi, thanks for your comment. I reproduced the problem with the test data, and I fixed it and pushed a commit. However, I realized that the current program calculate the bad RMS pixels for pedestal events. I'm not sure if it is needed or not, and so if you think it's not necessary, I can simply deactivate the calculation for pedestal events. Please let me know your opinion.

**Comment by YoshikiOhtani** [comment]
So I disabled the calculation of bad rms pixels for pedestal events, because I think it is not necessary. The tests run without any failure in local. It would be great if some could merge this branch, or I would merge this by myself if there are no objections.

**Review by aleberti — APPROVED** [review]

**Comment by YoshikiOhtani** [comment]
Thanks @aleberti for the approval. Deleting the branch now.

**Pull request merged**
